echo Testing $1 ...
echo Building image ...
docker build -t $1 dockerfiles/$1

echo Starting server ...
docker run -d --name=server --network=testnet $1

echo Running ldp-testsuite tester ...
docker run --network=testnet tester > reports/$1.txt

echo More testers to follow soon ...

echo Stopping server ...
docker stop server

echo Removing server ...
docker rm server
